server:
  port: 4000

spring:
  application:
    name: seal-auth
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

# feign 配置
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://47.107.152.93:22001/eureka/,http://120.79.101.221:22002/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
