server:
  port: 8888

spring:
  application:
    name: seal-config
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://47.107.152.93:22001/eureka/,http://120.79.101.221:22002/eureka/
